In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
data = {
    'Yil' : [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni' : [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp' : [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
}

In [7]:
df = pd.DataFrame(data) # lug'atda datafreym yaratish

In [8]:
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [9]:
df.head() #yuqoridagi 5 ta qiymatni qaytaradi

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [10]:
df.shape # datafreymning hajmini ko'rsatadi

(8, 3)