In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])

In [5]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [6]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [7]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [9]:
df.shape

(2499, 12)

In [12]:
df.sort_index(axis = 1, inplace = True)

In [13]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [16]:
df.sort_index(ascending = False) #teskari tartiblash, kamayish tartibida

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008

In [18]:
df.sort_values(by = 'price') # 'price' bo'yicha tartiblash

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
410,chevrolet,green,2 days left,usa,167425634,274706,door,0,arizona,salvage insurance,2gcec19h8s1195266,1995
330,ford,green,19 hours left,usa,167359712,296860,door,0,california,salvage insurance,1falp62w5th144314,1996
331,ford,red,17 hours left,usa,167610991,203158,door,0,illinois,salvage insurance,1fmzk04136ga07119,2006
339,ford,black,2 days left,usa,167360232,214800,door,0,south carolina,salvage insurance,3fafp37372r151014,2002
496,ford,red,17 hours left,usa,167357804,252588,pickup,0,oklahoma,salvage insurance,1ftef15n0tlc14455,1996
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017

In [20]:
df.sort_values(by = 'price', ascending = False) # kamayish tartibida tartiblash

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
141,dodge,orange,2 days left,usa,167756157,177948,van,0,utah,salvage insurance,2d8hn44h88r669549,2008
391,cadillac,white,9 days left,usa,167651218,105169,coupe,0,virginia,salvage insurance,1g6el12y9yu148063,2000
285,ford,black,17 hours left,usa,167251902,124969,door,0,oklahoma,salvage insurance,1fafp34p7yw270338,2000
290,mazda,gray,16 hours left,usa,167543177,117541,door,0,indiana,salvage insurance,jm3er293590215768,2009
354,ford,blue,2 days left,usa,167360535,180364,pickup,0,tennessee,salvage insurance,1ftyr10d19pa60391,2009

In [21]:
df.sort_values(by = ['price', 'mileage'])

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
309,chevrolet,maroon,18 hours left,usa,167418651,0,door,0,wyoming,salvage insurance,3gnek12t74g240524,2004
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
349,heartland,white,7 days left,usa,167266321,1,sundance,0,pennsylvania,clean vehicle,5sfgf29269e031344,2009
196,ford,white,2 days left,usa,167656523,76858,mpv,0,texas,clean vehicle,1fbax2cv0hkb32599,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017